backend:
  name: git-gateway
  branch: main

site_url: https://jekyll-decap-cms.netlify.app

publish_mode: simple # can be editorial_workflow

show_preview_links: true

media_folder: 'assets/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          display_fields: [name],
          search_fields: [name],
          value_field: 'name',
        }      
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'authors'
    label: 'Authors'
    label_singular: 'Author'
    folder: '_authors/'
    create: true
    identifier_field: name
    editor:
      preview: false
    fields:
      - { label: 'Pseudo', name: 'pseudo', widget: 'string' }
      - { label: 'Full Name', name: 'name', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown', required: False }
      - { label: 'Image', name: 'image', widget: 'image', required: False }

  - name: 'galleries'
    label: 'Galleries'
    label_singular: 'Gallery'
    folder: '_galleries'
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: True
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'gallery' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}", format: "YYYY/MM/DD", picker_utc: false }
      - { label: "Featured Image", name: "thumbnail", widget: "image", choose_url: true }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          display_fields: [name],
          search_fields: [name],
          value_field: 'name',
        }      
      - label: 'Images'
        name: 'images'
        widget: 'list'
        fields: 
          - { label: 'Image', name: 'url', widget: 'image' }
          - { label: 'Caption', name: 'caption', widget: 'string' }

  - name: pages-fr
    label: Pages FR
    label_singular: Page FR
    folder: pages-fr
    create: true

    fields:
      - label: Publiée
        name: published
        widget: boolean
        default: false

      - label: URL
        name: permalink
        widget: string

      - label: Catégorie
        name: categorie
        widget: relation
        collection: configuration
        file: categories
        search_fields: ["categories.*.name"]
        display_fields: ["categories.*.name"]
        value_field: "categories.*.name"

      - label: Title
        name: title
        widget: string

      - label: Introduction
        name: intro
        widget: markdown

      - label: Body
        name: body
        widget: markdown

      - label: Image principale
        name: main_img
        widget: image
        choose_url: false  

      - label: Galerie
        name: gallery
        widget: list
        field: 
          label: Image
          name: image
          widget: image
          choose_url: false

      - label: Ordre
        name: Ordre
        widget: number
        hint: Numérotation de 10 en 10 qui conditionne la position dans le menu

  - label: "Configuration"
    name: "configuration"
    files:

      - label: Catégories
        name: categories
        file: _data/categories.yml
        fields:
          - label: Catégories
            name: categories
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Position
                name: position
                widget: number
              - label: Est parent
                hint: Cette catégorie est-elle un point d'entrée dans le menu, comme "Hébergements" ou "Activités"
                name: is_parent
                widget: boolean
                default: true
